<!DOCTYPE html>
<html>
	<head>
		<?php echo $head; ?>{{prova}}
		<?php
			$out = str_repeat('<li>&bull;</li>', 27);
			if (isSet($nome)) {
				$out='';
				$a = str_split($nome);
				foreach($a as $char)$out.='<li>'.$char.'</li>';
			}
		?>
	</head>
	<body>
		<div id="item">
            <ul><?php echo $out; ?></ul>
        </div>
		[[prova &par1=`Foo` &par2=`evenMoreFoo`]]
		<br>
		[[xxx &name=`Federico`]]
		[D[URL_BASE]D]
		<hr>
		[T[perche]T] - [T[hello]T]
	</body>
</html>
