<?php
	$out = str_repeat('<li>&bull;</li>', 27);
	if (isSet($nome)) {
		$out='';
		$a = str_split($nome);
		foreach($a as $char)$out.='<li>'.$char.'</li>';
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<?php echo $head; ?>
	</head>
	<body>
		{{prova}}
		<div id="item">
            <ul><?php echo $out; ?></ul>
        </div>
		<!-- [[prova &par1=`Foo` &par2=`evenMoreFoo`]]
		<br>
		[[xxx &name=`Federico`]] -->
	
		<footer>
			<span>	
				<a href="[D[URL_BASE]D]">
					[D[URL_BASE]D]
				</a>
			</span>
			
			<span>[T[hello]T] [T[php]T]</span>
			<!-- <hr> -->
			<!-- <?php echo $data; ?>  -->
		</footer>
	</body>
</html>
